=== shihyu/MyTool/se/toolconfig/http/www.slickedit.com/dtd/vse/xmlformatting/1.0/xmlhtmlformatscheme.dtd
<!ELEMENT scheme (tag*)>
<!ELEMENT tag (generalSettings, contentWrapSettings, tagLayoutSettings)>
<!ELEMENT generalSettings (#PCDATA)>
<!ELEMENT contentWrapSettings (#PCDATA)>
<!ELEMENT tagLayoutSettings (#PCDATA)>
<!ATTLIST scheme name CDATA #REQUIRED
                 indentStyle CDATA #REQUIRED>
<!ATTLIST tag name CDATA #REQUIRED 
              usesDefault CDATA #REQUIRED>
<!ATTLIST generalSettings hasEndTag CDATA #REQUIRED
                          insertEndTag CDATA #REQUIRED
                          requiredEndTag CDATA #REQUIRED>
<!ATTLIST contentWrapSettings wrapMode         CDATA #REQUIRED
                         wrapMethod       CDATA #REQUIRED
                         fixedWidthCol    CDATA #REQUIRED
                         fixedWidthMRC    CDATA #REQUIRED 
                         autoWidthMRC     CDATA #REQUIRED 
                         fixedRightCol    CDATA #REQUIRED
                         useFixedWidthMRC CDATA #REQUIRED 
                         useAutoWidthHMRC  CDATA #REQUIRED 
                         includeTags      CDATA #REQUIRED
                         preserveWidth    CDATA #REQUIRED> 
<!ATTLIST tagLayoutSettings layoutStyle    CDATA #REQUIRED
                         indentMethod   CDATA #REQUIRED
                         indentFrom     CDATA #REQUIRED
                         indentSpaces   CDATA #REQUIRED 
                         linesBefore    CDATA #REQUIRED 
                         linesAfter     CDATA #REQUIRED
                         separateStartTag    CDATA #REQUIRED 
                         separateEndTag      CDATA #REQUIRED 
                         preserveLayout CDATA #REQUIRED
                         applyLayout    CDATA #REQUIRED>

=== shihyu/MyTool/mybin/se/sysconfig/formatschemes/xwschemes/xml.xml
<!DOCTYPE scheme SYSTEM "xmlhtmlformatscheme.dtd">
   <scheme
      name="xml"
      indentStyle="1"
      caseSensitive="1">
      <tag
         name="(default)"
         matchTagName="(no match)">
         <generalSettings
            hasEndTag="1"
            insertEndTag="1">
         </generalSettings>
         <contentWrapSettings
            wrapMode="1"
            wrapMethod="3"
            fixedWidthCol="65"
            fixedWidthMRC="80"
            autoWidthMRC="80"
            fixedRightCol="80"
            useFixedWidthMRC="0"
            useAutoWidthHMRC="0"
            includeTags="1"
            preserveWidth="0">
         </contentWrapSettings>
         <tagLayoutSettings
            indentMethod="1"
            indentFrom="1"
            indentSpaces="3"
            linesBefore="0"
            linesAfter="1"
            separateStartTag="1"
            separateEndTag="1"
            preserveLayout="0"
            applyLayout="0">
         </tagLayoutSettings>
      </tag>
      <tag
         name="(Block)"
         matchTagName="(no match)">
         <generalSettings
            hasEndTag="1"
            insertEndTag="1">
         </generalSettings>
         <contentWrapSettings
            wrapMode="1"
            wrapMethod="3"
            fixedWidthCol="65"
            fixedWidthMRC="80"
            autoWidthMRC="80"
            fixedRightCol="80"
            useFixedWidthMRC="0"
            useAutoWidthHMRC="0"
            includeTags="0"
            preserveWidth="0">
         </contentWrapSettings>
         <tagLayoutSettings
            indentMethod="1"
            indentFrom="1"
            indentSpaces="3"
            linesBefore="1"
            linesAfter="1"
            separateStartTag="1"
            separateEndTag="1"
            preserveLayout="0"
            applyLayout="0">
         </tagLayoutSettings>
      </tag>
      <tag
         name="(Treat as content)"
         matchTagName="(no match)">
         <generalSettings
            hasEndTag="1"
            insertEndTag="1">
         </generalSettings>
         <contentWrapSettings
            wrapMode="2"
            wrapMethod="3"
            fixedWidthCol="65"
            fixedWidthMRC="80"
            autoWidthMRC="80"
            fixedRightCol="80"
            useFixedWidthMRC="0"
            useAutoWidthHMRC="0"
            includeTags="1"
            preserveWidth="0">
         </contentWrapSettings>
         <tagLayoutSettings
            indentMethod="1"
            indentFrom="1"
            indentSpaces="3"
            linesBefore="0"
            linesAfter="1"
            separateStartTag="1"
            separateEndTag="1"
            preserveLayout="0"
            applyLayout="0">
         </tagLayoutSettings>
      </tag>
      <tag
         name="(Preserve content)"
         matchTagName="(no match)">
         <generalSettings
            hasEndTag="1"
            insertEndTag="1">
         </generalSettings>
         <contentWrapSettings
            wrapMode="3"
            wrapMethod="3"
            fixedWidthCol="65"
            fixedWidthMRC="80"
            autoWidthMRC="80"
            fixedRightCol="80"
            useFixedWidthMRC="0"
            useAutoWidthHMRC="0"
            includeTags="1"
            preserveWidth="0">
         </contentWrapSettings>
         <tagLayoutSettings
            indentMethod="1"
            indentFrom="1"
            indentSpaces="3"
            linesBefore="1"
            linesAfter="1"
            separateStartTag="1"
            separateEndTag="1"
            preserveLayout="0"
            applyLayout="0">
         </tagLayoutSettings>
      </tag>
      <tag
         name="(Semi-block)"
         matchTagName="(no match)">
         <generalSettings
            hasEndTag="1"
            insertEndTag="1">
         </generalSettings>
         <contentWrapSettings
            wrapMode="1"
            wrapMethod="3"
            fixedWidthCol="65"
            fixedWidthMRC="80"
            autoWidthMRC="80"
            fixedRightCol="80"
            useFixedWidthMRC="0"
            useAutoWidthHMRC="0"
            includeTags="1"
            preserveWidth="0">
         </contentWrapSettings>
         <tagLayoutSettings
            indentMethod="1"
            indentFrom="1"
            indentSpaces="3"
            linesBefore="1"
            linesAfter="1"
            separateStartTag="0"
            separateEndTag="0"
            preserveLayout="0"
            applyLayout="0">
         </tagLayoutSettings>
      </tag>
   </scheme>
